from django.conf.urls.defaults import *


urlpatterns = patterns('friends.views',
    url(r'^$',
        'friend_list',
        name='friends_home'),
    url(r'^list/(?P<username>\w+)/$',
        'friend_list',
        name='friend_list'),
    url(r'^add/(?P<username>\w+)/$',
        'friendship_request',
        name='friendship_request'),
    url(r'^accept/(?P<username>\w+)/$',
        'friendship_accept',
        name='friendship_accept'),
    url(r'^decline/(?P<username>\w+)/$',
        'friendship_decline',
        name='friendship_decline'),
    url(r'^cancel/(?P<username>\w+)/$',
        'friendship_cancel',
        name='friendship_cancel'),
    url(r'^delete/(?P<username>\w+)/$',
        'friendship_delete',
        name='friendship_delete'),
    url(r'^block/(?P<username>\w+)/$',
        'block_user',
        name='block_user'),
    url(r'^unblock/(?P<username>\w+)/$',
        'unblock_user',
        name='unblock_user'),
)
